# Generated by Django 4.1.1 on 2023-08-10 01:49

from django.db import migrations, models
import django.db.models.deletion
import laboratorio.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lab_nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_nombre', models.CharField(max_length=200, unique=True)),
                ('f_fabricacion', models.DateField(validators=[laboratorio.models.Min_year])),
                ('p_costo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('p_venta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pro_laboratorio', models.OneToOneField(blank=True, db_column='lab_nombre', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='laboratorio.laboratorio')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='DirectorGeneral',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dir_nombre', models.CharField(max_length=200)),
                ('laboratorio', models.OneToOneField(blank=True, db_column='lab_nombre', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='laboratorio.laboratorio')),
            ],
        ),
    ]
