# Generated by Django 4.1.1 on 2023-08-14 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0002_actualizado_campos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directorgeneral',
            old_name='id',
            new_name='id_dir',
        ),
        migrations.RenameField(
            model_name='laboratorio',
            old_name='id',
            new_name='id_lab',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='id',
            new_name='id_pro',
        ),
        migrations.AlterField(
            model_name='directorgeneral',
            name='laboratorio',
            field=models.OneToOneField(blank=True, db_column='id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='laboratorio.laboratorio'),
        ),
    ]
