# Generated by Django 4.1.1 on 2023-08-14 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0003_rename_id_directorgeneral_id_dir_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laboratorio',
            options={'ordering': ['-id'], 'verbose_name': 'laboratorio', 'verbose_name_plural': 'Labs'},
        ),
        migrations.RenameField(
            model_name='laboratorio',
            old_name='id_lab',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='id_pro',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='directorgeneral',
            name='laboratorio',
            field=models.OneToOneField(blank=True, db_column='lab_nombre', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='laboratorio.laboratorio'),
        ),
        migrations.AlterModelTable(
            name='directorgeneral',
            table='directorgeneral',
        ),
        migrations.AlterModelTable(
            name='laboratorio',
            table='laboratorio',
        ),
    ]
